### ISSUE TITLE
onderzoeken hoe submodules te gebruiken in github

### ISSUE THREAD

**Issue by hvanreenen** [NLHEALTHCARE/CLINICAL_DATAVAULT#10]
Er is nogal een wildgroei aan het ontstaan in github.
Sommige repos horen bij elkaar. De issues met backlog horen dan ook bij elkaar.

Graag onderzoeken hoe submodules te gebruiken in github, met daaraan ook gekoppeld de issues vis huboard.

**Comment by dkapitan** [comment]
@hvanreenen 

Ik pak deze rol op als Product Owner. Heb de repos al een beetje opgeschoond. Repositories die bij elkaar horen als een geheel, worden als project gemanaged. Zie b.v. dus [Clinics DWH2.0 project](https://github.com/orgs/NLHEALTHCARE/projects/14)
