### ISSUE TITLE
vektis_agb reflect error

### ISSUE THREAD

**Issue by costiaanmesu** [NLHEALTHCARE/CLINICAL_DATAVAULT#17]
Als een sor_tabel nog niet bestaat en er geen bronbestand is voor 1 van de onderdelen komt er een fatale error: File "C:\Program Files\Python35\lib\site-packages\sqlalchemy\dialects\postgresql\base.py", line 2272, in get_table_oid raise exc.NoSuchTableError(table_name) sqlalchemy.exc.NoSuchTableError.. Een legitiem voorbeeld is bijvoorbeeld; ik wil alleen huisartsen inlezen, voor hen bestaat geen fagbx21 bestand. Dat is inhoudelijk geen fout. Technisch wel.

**Comment by dkapitan** [comment]
Obsolete, verplaatst naar https://github.com/NLHEALTHCARE/FHIRVAULT-VALUESETS/issues/2
