### ISSUE TITLE
Primary key constraint op dv.zorgaanbieder_sat_adres maakt het onmogelijk meerdere adressen per zorgaanbieder vast te leggen.

### ISSUE THREAD

**Issue by costiaanmesu** [NLHEALTHCARE/CLINICAL_DATAVAULT#18]

**Comment by costiaanmesu** [comment]
In de AGB bestanden worden o.a. meerdere adressen aangeleverd. Nu een filter aangebracht om adres met volgnummer 1 te kiezen. Dat werkt prima. Theoretisch zou je echter de andere adressen ook willen kunnen bewaren denk ik?

**Comment by dkapitan** [comment]
This issue was moved to NLHEALTHCARE/PYELT#26
