### ISSUE TITLE
vektis agb op shannon test draaien

### ISSUE THREAD

**Issue by hvanreenen** [NLHEALTHCARE/CLINICAL_DATAVAULT#4]

**Comment by RFWiegerinck** [comment]
Wat is onze definitie van 'review'? 'Working' heb ik nu volgens mij afgerond. Moet ik, een andere reviewer of eerst ik en dan een andere nu de 'review' fase doen?

**Comment by costiaanmesu** [comment]
Unzippen werkt niet op de Shannon.

**Comment by costiaanmesu** [comment]
Perfomance is bij inladen van alle agb codes zo slecht dat het lijkt alsof deze hangt. Kunnen we dit nog verbeteren?

**Comment by costiaanmesu** [comment]
Zonder uitgepakte zipfiles crasht vektis_agb_proces omdat "de tabel fagbx20_hstage niet gevonden kan worden".

**Comment by costiaanmesu** [comment]
ZIP issue is opgelost. LINUX OS is case sensitive. _.zip was in lowercase geschreven in de code terwijl de bestandsnamen uppercase waren. code is nu: glob.glob('_.zip') or glob.glob('*.ZIP')

**Comment by costiaanmesu** [comment]
Genereren van csv bestanden gaat over zijn nek op encoding: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc9 in position 268: invalid continuation byte

**Comment by costiaanmesu** [comment]
Opgelost door encoding expliciet toe te voegen: file_wrapper = io.TextIOWrapper(io.BytesIO(binary_str), encoding='cp1252')

**Comment by costiaanmesu** [comment]
duplicate key errors sor_dv (bij fagbx23? Praktijknummer?)

**Comment by costiaanmesu** [comment]
Duplicate keys worden veroorzaakt doordat Ondernemingen en Zorgverleners overeenkomende agb codes  kunnen hebben zonder dat het om dezelfde partijen gaat (deze staan los van elkaar). Je zou dus Zorgverlener / Onderneming op moeten nemen in de bk.

**Comment by costiaanmesu** [comment]
Ik heb de agb code in de sat identificatie aangepast naar de volledige 8 posities

**Comment by costiaanmesu** [comment]
Zorgverlener hub/sat wordt niet aangemaakt. Waarschijnlijk vanwege overerving. cls._base_ is medewerker, geen dventity, oplossen met dventity in cls.__bases__? Verder doorvoeren:     @classmethod
    def get_class_with_dventity_base(cls) -> 'DvEntity':
        for base in cls.__bases__:
            if base == DvEntity:
                return cls
            elif hasattr(base, "get_class_with_dventity_base"):
                return base.get_class_with_dventity_base()

**Comment by dkapitan** [comment]
Obsolete: verplaatst naar nieuwe repo
https://github.com/NLHEALTHCARE/FHIRVAULT-VALUESETS/issues/2
